// Version 1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: hyperliquid.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_hyperliquid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded object conforming to files of HyperLiquid data dir "replica_cmds"
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_hyperliquid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderBookSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded object conforming to a HyperLiquid order book snapshot
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookSnapshot) Reset() {
	*x = OrderBookSnapshot{}
	mi := &file_hyperliquid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookSnapshot) ProtoMessage() {}

func (x *OrderBookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookSnapshot.ProtoReflect.Descriptor instead.
func (*OrderBookSnapshot) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_rawDescGZIP(), []int{2}
}

func (x *OrderBookSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockFills struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded object conforming to files of HyperLiquid data dir "node_fills"
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFills) Reset() {
	*x = BlockFills{}
	mi := &file_hyperliquid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFills) ProtoMessage() {}

func (x *BlockFills) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFills.ProtoReflect.Descriptor instead.
func (*BlockFills) Descriptor() ([]byte, []int) {
	return file_hyperliquid_proto_rawDescGZIP(), []int{3}
}

func (x *BlockFills) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_hyperliquid_proto protoreflect.FileDescriptor

const file_hyperliquid_proto_rawDesc = "" +
	"\n" +
	"\x11hyperliquid.proto\x12\x19hyperliquid_l1_gateway.v1\")\n" +
	"\tTimestamp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x1b\n" +
	"\x05Block\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"'\n" +
	"\x11OrderBookSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\" \n" +
	"\n" +
	"BlockFills\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xb9\x03\n" +
	"\x14HyperLiquidL1Gateway\x12l\n" +
	"\x14GetOrderBookSnapshot\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a,.hyperliquid_l1_gateway.v1.OrderBookSnapshot\"\x00\x12Z\n" +
	"\fStreamBlocks\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a .hyperliquid_l1_gateway.v1.Block\"\x000\x01\x12r\n" +
	"\x18StreamOrderBookSnapshots\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a,.hyperliquid_l1_gateway.v1.OrderBookSnapshot\"\x000\x01\x12c\n" +
	"\x10StreamBlockFills\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a%.hyperliquid_l1_gateway.v1.BlockFills\"\x000\x01B\x0eZ\finternal/apib\x06proto3"

var (
	file_hyperliquid_proto_rawDescOnce sync.Once
	file_hyperliquid_proto_rawDescData []byte
)

func file_hyperliquid_proto_rawDescGZIP() []byte {
	file_hyperliquid_proto_rawDescOnce.Do(func() {
		file_hyperliquid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperliquid_proto_rawDesc), len(file_hyperliquid_proto_rawDesc)))
	})
	return file_hyperliquid_proto_rawDescData
}

var file_hyperliquid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hyperliquid_proto_goTypes = []any{
	(*Timestamp)(nil),         // 0: hyperliquid_l1_gateway.v1.Timestamp
	(*Block)(nil),             // 1: hyperliquid_l1_gateway.v1.Block
	(*OrderBookSnapshot)(nil), // 2: hyperliquid_l1_gateway.v1.OrderBookSnapshot
	(*BlockFills)(nil),        // 3: hyperliquid_l1_gateway.v1.BlockFills
}
var file_hyperliquid_proto_depIdxs = []int32{
	0, // 0: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.GetOrderBookSnapshot:input_type -> hyperliquid_l1_gateway.v1.Timestamp
	0, // 1: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamBlocks:input_type -> hyperliquid_l1_gateway.v1.Timestamp
	0, // 2: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamOrderBookSnapshots:input_type -> hyperliquid_l1_gateway.v1.Timestamp
	0, // 3: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamBlockFills:input_type -> hyperliquid_l1_gateway.v1.Timestamp
	2, // 4: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.GetOrderBookSnapshot:output_type -> hyperliquid_l1_gateway.v1.OrderBookSnapshot
	1, // 5: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamBlocks:output_type -> hyperliquid_l1_gateway.v1.Block
	2, // 6: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamOrderBookSnapshots:output_type -> hyperliquid_l1_gateway.v1.OrderBookSnapshot
	3, // 7: hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway.StreamBlockFills:output_type -> hyperliquid_l1_gateway.v1.BlockFills
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hyperliquid_proto_init() }
func file_hyperliquid_proto_init() {
	if File_hyperliquid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperliquid_proto_rawDesc), len(file_hyperliquid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperliquid_proto_goTypes,
		DependencyIndexes: file_hyperliquid_proto_depIdxs,
		MessageInfos:      file_hyperliquid_proto_msgTypes,
	}.Build()
	File_hyperliquid_proto = out.File
	file_hyperliquid_proto_goTypes = nil
	file_hyperliquid_proto_depIdxs = nil
}
